In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_excel(r'embeddingsdata - Copy.xlsx')
df.head()

Label   embed_0   embed_1   embed_2   embed_3   embed_4   embed_5  \
0      0  0.009625 -0.029216  0.027109  0.023631 -0.004972  0.031757   
1      0 -0.007535 -0.039844  0.030167  0.031224  0.004742  0.028289   
2      0  0.022408 -0.030840  0.032328  0.046965  0.007798  0.025860   
3      0  0.019677 -0.034055  0.012662  0.070387 -0.011170  0.017842   
4      0  0.017678 -0.030323  0.012829  0.065267 -0.025161  0.011964   

    embed_6   embed_7   embed_8  ...  embed_758  embed_759  embed_760  \
0 -0.045125  0.044483  0.019400  ...  -0.045697  -0.001972  -0.008154   
1 -0.068723  0.039153  0.019596  ...  -0.056834   0.008613  -0.006578   
2 -0.065093  0.035118  0.035359  ...  -0.016249   0.020413  -0.034288   
3 -0.050945  0.044878  0.034781  ...  -0.038879   0.002963  -0.018754   
4 -0.050590  0.042820  0.029161  ...  -0.042079   0.010192  -0.010147   

   embed_761  embed_762  embed_763  embed_764  embed_765  embed_766  embed_767  
0  -0.056139   0.009890   0.042366   0.040134   0.009304  -0.016137  -0.009309  
1  -0.034220   0.027574   0.045456   0.027402   0.017837  -0.035009  -0.010062  
2  -0.050649   0.028408   0.040412   0.030261   0.003535  -0.034122  -0.017289  
3  -0.053278   0.033005   0.031635   0.022544  -0.011774  -0.011125  -0.017540  
4  -0.035857   0.021784   0.034621   0.017342  -0.009884  -0.010316  -0.029238  

[5 rows x 769 columns]

## A1

Train a support vector machine using the training set obtained from above exerciseyou’re yourdataset has multiple classes, take any two classes for this exercise.

In [5]:
X = df[df.columns[1:]]
y = df['Label']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [8]:
from sklearn import svm

In [9]:
clf= svm.SVC()

In [10]:
clf.fit(X_train,y_train)

SVC()

In [11]:
clf.support_vectors_

array([[ 0.01455336, -0.03024836,  0.01896371, ...,  0.00770176,
        -0.01886826, -0.02149862],
       [ 0.00868154, -0.0291283 ,  0.03167596, ...,  0.00350518,
        -0.02659446, -0.02214345],
       [ 0.00423006, -0.03914441,  0.01262215, ...,  0.01100539,
        -0.03064076, -0.04991988],
       ...,
       [-0.01633175, -0.00580312,  0.0140028 , ..., -0.00251815,
        -0.02201059, -0.00518822],
       [ 0.00090481, -0.02699681,  0.00107208, ...,  0.01125898,
        -0.02177747, -0.014525  ],
       [-0.00458735, -0.03566458,  0.00960748, ...,  0.01745316,
        -0.01321469, -0.01471795]])

## A2

Test the accuracy of the SVM using the test set obtained from above exercise. Following code for help.

In [12]:
clf.score(X_test,y_test)

0.5851851851851851

## A3

 Use the Predict function of SVC classifier to study the output values of the classifier. Relate the output value to the class value predicted. Test the accuracy of the SVM, with your own logic of class determination and comparing against the class labels, using the test set obtained from above exercise. Following code for help.

In [16]:
pred = clf.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix, classification_report

In [17]:
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[100   5   0   0   0   0   0   0   0   0   0]
 [ 14  58   0   0   0   0   0   0   0   0   0]
 [ 29   2   0   0   0   0   0   0   0   0   0]
 [  3   2   0   0   0   0   0   0   0   0   0]
 [  7   0   0   0   0   0   0   0   0   0   0]
 [ 14   3   0   0   0   0   0   0   0   0   0]
 [ 11   0   0   0   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0   0   0]
 [ 10   0   0   0   0   0   0   0   0   0   0]
 [  6   0   0   0   0   0   0   0   0   0   0]]
              precision    recall  f1-score   support

           0       0.51      0.95      0.66       105
           1       0.78      0.81      0.79        72
           2       0.00      0.00      0.00        31
           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00         7
           5       0.00      0.00      0.00        17
           6       0.00      0.00      0.00        11
           7       0.00      0.00      0.00      

C:\Users\Pranav\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Pranav\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Pranav\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

## A4

Experiment with various kernel functions (‘linear’, ‘poly’, ‘rbf’&‘sigmoid’) to train and test the accuracy of the models.

In [23]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

kernels = ['linear', 'poly', 'rbf', 'sigmoid']

for kernel in kernels:
    svm = SVC(kernel=kernel, random_state=42)
    svm.fit(X_train, y_train)
    y_pred = svm.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Kernel: {kernel}, Accuracy: {accuracy:.4f}")

Kernel: linear, Accuracy: 0.5815
Kernel: poly, Accuracy: 0.5852
Kernel: rbf, Accuracy: 0.5852
Kernel: sigmoid, Accuracy: 0.5667


#### This code is written only by Prabhav Ravi Tammanashastri